version: '3.8'

services:
  django-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://admin:password@postgres:5432/django_db
    networks:
      - django-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - django-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django-network

volumes:
  redis_data:
  postgres_data:

networks:
  django-network:
    driver: bridge