version: '3.8'

services:
  # Frontend (React)
  frontend:
    build: ../mern-ecommerce/frontend
    ports:
      - "3000:3000"
    depends_on:
      - golang-api
      - django-app
    networks:
      - fullstack-network

  # Golang API Gateway
  golang-api:
    build: ../golang-api
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
    networks:
      - fullstack-network

  # Java Microservices
  user-service:
    build: ../spring-boot-microservices/user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - fullstack-network

  product-service:
    build: ../spring-boot-microservices/product-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - fullstack-network

  # Django + Redis
  django-app:
    build: ../django-redis-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://admin:password@postgres:5432/fullstack_db
    networks:
      - fullstack-network

  # Databases
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fullstack_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fullstack-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fullstack-network

  # Caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fullstack-network

  # Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - golang-api
      - django-app
    networks:
      - fullstack-network

volumes:
  postgres_data:
  mysql_data:
  mongo_data:
  redis_data:

networks:
  fullstack-network:
    driver: bridge