version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: microservices_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  postgres_data:

networks:
  microservices-network:
    driver: bridge